# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import mo_finder_pb2 as mo__finder__pb2


class MOFinderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMOsByFilters = channel.unary_stream(
                '/mo_finder.MOFinder/GetMOsByFilters',
                request_serializer=mo__finder__pb2.RequestGetMOsByFilters.SerializeToString,
                response_deserializer=mo__finder__pb2.ResponseGetMOsByFilters.FromString,
                )


class MOFinderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMOsByFilters(self, request, context):
        """get MO by filters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MOFinderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMOsByFilters': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMOsByFilters,
                    request_deserializer=mo__finder__pb2.RequestGetMOsByFilters.FromString,
                    response_serializer=mo__finder__pb2.ResponseGetMOsByFilters.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mo_finder.MOFinder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MOFinder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMOsByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/mo_finder.MOFinder/GetMOsByFilters',
            mo__finder__pb2.RequestGetMOsByFilters.SerializeToString,
            mo__finder__pb2.ResponseGetMOsByFilters.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
