# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mo_finder.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fmo_finder.proto\x12\tmo_finder\"|\n\x16RequestGetMOsByFilters\x12\x0e\n\x06tmo_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x66ilters\x18\x02 \x01(\t\x12\x0e\n\x06mo_ids\x18\x03 \x03(\x03\x12\r\n\x05p_ids\x18\x04 \x03(\x03\x12\x10\n\x08tprm_ids\x18\x05 \x03(\x03\x12\x10\n\x08only_ids\x18\x06 \x01(\x08\"&\n\x17ResponseGetMOsByFilters\x12\x0b\n\x03mos\x18\x01 \x03(\t2h\n\x08MOFinder\x12\\\n\x0fGetMOsByFilters\x12!.mo_finder.RequestGetMOsByFilters\x1a\".mo_finder.ResponseGetMOsByFilters\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mo_finder_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTGETMOSBYFILTERS']._serialized_start=30
  _globals['_REQUESTGETMOSBYFILTERS']._serialized_end=154
  _globals['_RESPONSEGETMOSBYFILTERS']._serialized_start=156
  _globals['_RESPONSEGETMOSBYFILTERS']._serialized_end=194
  _globals['_MOFINDER']._serialized_start=196
  _globals['_MOFINDER']._serialized_end=300
# @@protoc_insertion_point(module_scope)
