# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import zeebe_severity_pb2 as zeebe__severity__pb2


class SeverityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSeverityByFilters = channel.unary_unary(
                '/zeebe.severity.Severity/GetSeverityByFilters',
                request_serializer=zeebe__severity__pb2.FilterInput.SerializeToString,
                response_deserializer=zeebe__severity__pb2.ListResponseSeverity.FromString,
                )
        self.GetSeverityByRanges = channel.unary_unary(
                '/zeebe.severity.Severity/GetSeverityByRanges',
                request_serializer=zeebe__severity__pb2.ByRangesInput.SerializeToString,
                response_deserializer=zeebe__severity__pb2.ListResponseSeverity.FromString,
                )
        self.GetProcesses = channel.unary_unary(
                '/zeebe.severity.Severity/GetProcesses',
                request_serializer=zeebe__severity__pb2.ProcessesInput.SerializeToString,
                response_deserializer=zeebe__severity__pb2.ProcessesResponse.FromString,
                )
        self.GetSeverityByHierarchy = channel.unary_unary(
                '/zeebe.severity.Severity/GetSeverityByHierarchy',
                request_serializer=zeebe__severity__pb2.ByHierarchyInput.SerializeToString,
                response_deserializer=zeebe__severity__pb2.ListResponseSeverity.FromString,
                )
        self.GetProcessInstanceForSpecialTMO = channel.unary_stream(
                '/zeebe.severity.Severity/GetProcessInstanceForSpecialTMO',
                request_serializer=zeebe__severity__pb2.GetProcessInstanceForSpecialTMORequest.SerializeToString,
                response_deserializer=zeebe__severity__pb2.GetProcessInstanceForSpecialTMOResponse.FromString,
                )
        self.GetChildObjectsWithProcessInstance = channel.unary_stream(
                '/zeebe.severity.Severity/GetChildObjectsWithProcessInstance',
                request_serializer=zeebe__severity__pb2.GetChildObjectsWithProcessInstanceRequest.SerializeToString,
                response_deserializer=zeebe__severity__pb2.GetChildObjectsWithProcessInstanceResponse.FromString,
                )


class SeverityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSeverityByFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeverityByRanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeverityByHierarchy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcessInstanceForSpecialTMO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChildObjectsWithProcessInstance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SeverityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSeverityByFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeverityByFilters,
                    request_deserializer=zeebe__severity__pb2.FilterInput.FromString,
                    response_serializer=zeebe__severity__pb2.ListResponseSeverity.SerializeToString,
            ),
            'GetSeverityByRanges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeverityByRanges,
                    request_deserializer=zeebe__severity__pb2.ByRangesInput.FromString,
                    response_serializer=zeebe__severity__pb2.ListResponseSeverity.SerializeToString,
            ),
            'GetProcesses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcesses,
                    request_deserializer=zeebe__severity__pb2.ProcessesInput.FromString,
                    response_serializer=zeebe__severity__pb2.ProcessesResponse.SerializeToString,
            ),
            'GetSeverityByHierarchy': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeverityByHierarchy,
                    request_deserializer=zeebe__severity__pb2.ByHierarchyInput.FromString,
                    response_serializer=zeebe__severity__pb2.ListResponseSeverity.SerializeToString,
            ),
            'GetProcessInstanceForSpecialTMO': grpc.unary_stream_rpc_method_handler(
                    servicer.GetProcessInstanceForSpecialTMO,
                    request_deserializer=zeebe__severity__pb2.GetProcessInstanceForSpecialTMORequest.FromString,
                    response_serializer=zeebe__severity__pb2.GetProcessInstanceForSpecialTMOResponse.SerializeToString,
            ),
            'GetChildObjectsWithProcessInstance': grpc.unary_stream_rpc_method_handler(
                    servicer.GetChildObjectsWithProcessInstance,
                    request_deserializer=zeebe__severity__pb2.GetChildObjectsWithProcessInstanceRequest.FromString,
                    response_serializer=zeebe__severity__pb2.GetChildObjectsWithProcessInstanceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zeebe.severity.Severity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Severity(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSeverityByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zeebe.severity.Severity/GetSeverityByFilters',
            zeebe__severity__pb2.FilterInput.SerializeToString,
            zeebe__severity__pb2.ListResponseSeverity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSeverityByRanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zeebe.severity.Severity/GetSeverityByRanges',
            zeebe__severity__pb2.ByRangesInput.SerializeToString,
            zeebe__severity__pb2.ListResponseSeverity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProcesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zeebe.severity.Severity/GetProcesses',
            zeebe__severity__pb2.ProcessesInput.SerializeToString,
            zeebe__severity__pb2.ProcessesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSeverityByHierarchy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/zeebe.severity.Severity/GetSeverityByHierarchy',
            zeebe__severity__pb2.ByHierarchyInput.SerializeToString,
            zeebe__severity__pb2.ListResponseSeverity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProcessInstanceForSpecialTMO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/zeebe.severity.Severity/GetProcessInstanceForSpecialTMO',
            zeebe__severity__pb2.GetProcessInstanceForSpecialTMORequest.SerializeToString,
            zeebe__severity__pb2.GetProcessInstanceForSpecialTMOResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChildObjectsWithProcessInstance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/zeebe.severity.Severity/GetChildObjectsWithProcessInstance',
            zeebe__severity__pb2.GetChildObjectsWithProcessInstanceRequest.SerializeToString,
            zeebe__severity__pb2.GetChildObjectsWithProcessInstanceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
