from enum import Enum


class ZeebeProcessInstanceIntents(Enum):
    ELEMENT_ACTIVATING = "ELEMENT_ACTIVATING"
    ELEMENT_ACTIVATED = "ELEMENT_ACTIVATED"
    ELEMENT_COMPLETING = "ELEMENT_COMPLETING"
    ELEMENT_COMPLETED = "ELEMENT_COMPLETED"
    ELEMENT_TERMINATING = "ELEMENT_TERMINATING"
    ELEMENT_TERMINATED = "ELEMENT_TERMINATED"
    EXTERNALLY_TERMINATED = "EXTERNALLY_TERMINATED"


class CamundaOperateStatuses(Enum):
    ACTIVE = "ACTIVE"
    COMPLETED = "COMPLETED"
    CANCELED = "CANCELED"
    EXTERNALLY_TERMINATED = "EXTERNALLY_TERMINATED"
