# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: from_group_to_search.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x66rom_group_to_search.proto\x12\x0cgroup_search\"\xae\x01\n\x13RequestGetProcesses\x12\x11\n\tuser_data\x18\x01 \x01(\t\x12\x0e\n\x06tmo_id\x18\x02 \x01(\x03\x12\x14\n\x0c\x66ilters_list\x18\x03 \x01(\t\x12\x0c\n\x04sort\x18\x04 \x01(\t\x12\x15\n\rfind_by_value\x18\x05 \x01(\t\x12\x13\n\x0bwith_groups\x18\x06 \x01(\x08\x12\r\n\x05limit\x18\x07 \x01(\t\x12\x15\n\rranges_object\x18\x08 \x01(\t\"\xdd\x01\n\x19RequestGetProcessesGroups\x12\x11\n\tuser_data\x18\x01 \x01(\t\x12\x0e\n\x06tmo_id\x18\x02 \x01(\x03\x12\x14\n\x0c\x66ilters_list\x18\x03 \x01(\t\x12\x0c\n\x04sort\x18\x04 \x01(\t\x12\x15\n\rfind_by_value\x18\x05 \x01(\t\x12\x13\n\x0bwith_groups\x18\x06 \x01(\x08\x12\r\n\x05limit\x18\x07 \x01(\t\x12\x15\n\rranges_object\x18\x08 \x01(\t\x12\x10\n\x08group_by\x18\t \x01(\t\x12\x15\n\rmin_group_qty\x18\n \x01(\x05\"\"\n\x14ResponseGetProcesses\x12\n\n\x02mo\x18\x01 \x01(\t\"=\n\x0fProcessGroupKey\x12\x12\n\ngrouped_by\x18\x01 \x01(\t\x12\x16\n\x0egrouping_value\x18\x02 \x01(\t\"T\n\x12ProcessesGroupItem\x12,\n\x05group\x18\x01 \x03(\x0b\x32\x1d.group_search.ProcessGroupKey\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"I\n\x17ResponseProcessesGroups\x12.\n\x04item\x18\x01 \x01(\x0b\x32 .group_search.ProcessesGroupItem\"S\n\x16RequestGetMOsByFilters\x12\x0e\n\x06tmo_id\x18\x01 \x01(\x03\x12\x14\n\x0c\x66ilters_list\x18\x02 \x01(\t\x12\x13\n\x0bwith_groups\x18\x03 \x01(\x08\"&\n\x17ResponseGetMOsByFilters\x12\x0b\n\x03mos\x18\x01 \x03(\t2\xb6\x02\n\x0bGroupSearch\x12Y\n\x0cGetProcesses\x12!.group_search.RequestGetProcesses\x1a\".group_search.ResponseGetProcesses\"\x00\x30\x01\x12h\n\x12GetProcessesGroups\x12\'.group_search.RequestGetProcessesGroups\x1a%.group_search.ResponseProcessesGroups\"\x00\x30\x01\x12\x62\n\x0fGetMOsByFilters\x12$.group_search.RequestGetMOsByFilters\x1a%.group_search.ResponseGetMOsByFilters\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'from_group_to_search_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTGETPROCESSES']._serialized_start=45
  _globals['_REQUESTGETPROCESSES']._serialized_end=219
  _globals['_REQUESTGETPROCESSESGROUPS']._serialized_start=222
  _globals['_REQUESTGETPROCESSESGROUPS']._serialized_end=443
  _globals['_RESPONSEGETPROCESSES']._serialized_start=445
  _globals['_RESPONSEGETPROCESSES']._serialized_end=479
  _globals['_PROCESSGROUPKEY']._serialized_start=481
  _globals['_PROCESSGROUPKEY']._serialized_end=542
  _globals['_PROCESSESGROUPITEM']._serialized_start=544
  _globals['_PROCESSESGROUPITEM']._serialized_end=628
  _globals['_RESPONSEPROCESSESGROUPS']._serialized_start=630
  _globals['_RESPONSEPROCESSESGROUPS']._serialized_end=703
  _globals['_REQUESTGETMOSBYFILTERS']._serialized_start=705
  _globals['_REQUESTGETMOSBYFILTERS']._serialized_end=788
  _globals['_RESPONSEGETMOSBYFILTERS']._serialized_start=790
  _globals['_RESPONSEGETMOSBYFILTERS']._serialized_end=828
  _globals['_GROUPSEARCH']._serialized_start=831
  _globals['_GROUPSEARCH']._serialized_end=1141
# @@protoc_insertion_point(module_scope)
