# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etransfer.proto\"\x07\n\x05\x45mpty\"\x80\x02\n\nPermission\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x16\n\tparent_id\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\npermission\x18\x03 \x01(\t\x12\x17\n\x0fpermission_name\x18\x04 \x01(\t\x12\x1f\n\x12root_permission_id\x18\x05 \x01(\x05H\x01\x88\x01\x01\x12\x0c\n\x04read\x18\x06 \x01(\x08\x12\x0e\n\x06\x64\x65lete\x18\x07 \x01(\x08\x12\x0e\n\x06\x61\x63tive\x18\x08 \x01(\x08\x12\x0e\n\x06\x63reate\x18\t \x01(\x08\x12\x0e\n\x06update\x18\n \x01(\x08\x12\r\n\x05\x61\x64min\x18\x0b \x01(\x08\x42\x0c\n\n_parent_idB\x15\n\x13_root_permission_id\"1\n\x0eListPermission\x12\x1f\n\npermission\x18\x01 \x03(\x0b\x32\x0b.Permission2\x9c\x01\n\x08Transfer\x12/\n\x10GetTMOPermission\x12\x06.Empty\x1a\x0f.ListPermission\"\x00\x30\x01\x12.\n\x0fGetMOPermission\x12\x06.Empty\x1a\x0f.ListPermission\"\x00\x30\x01\x12/\n\x10GetTPMPermission\x12\x06.Empty\x1a\x0f.ListPermission\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transfer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_PERMISSION']._serialized_start=28
  _globals['_PERMISSION']._serialized_end=284
  _globals['_LISTPERMISSION']._serialized_start=286
  _globals['_LISTPERMISSION']._serialized_end=335
  _globals['_TRANSFER']._serialized_start=338
  _globals['_TRANSFER']._serialized_end=494
# @@protoc_insertion_point(module_scope)
