# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import transfer_pb2 as transfer__pb2


class TransferStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTMOPermission = channel.unary_stream(
                '/Transfer/GetTMOPermission',
                request_serializer=transfer__pb2.Empty.SerializeToString,
                response_deserializer=transfer__pb2.ListPermission.FromString,
                )
        self.GetMOPermission = channel.unary_stream(
                '/Transfer/GetMOPermission',
                request_serializer=transfer__pb2.Empty.SerializeToString,
                response_deserializer=transfer__pb2.ListPermission.FromString,
                )
        self.GetTPMPermission = channel.unary_stream(
                '/Transfer/GetTPMPermission',
                request_serializer=transfer__pb2.Empty.SerializeToString,
                response_deserializer=transfer__pb2.ListPermission.FromString,
                )


class TransferServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTMOPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMOPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTPMPermission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransferServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTMOPermission': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTMOPermission,
                    request_deserializer=transfer__pb2.Empty.FromString,
                    response_serializer=transfer__pb2.ListPermission.SerializeToString,
            ),
            'GetMOPermission': grpc.unary_stream_rpc_method_handler(
                    servicer.GetMOPermission,
                    request_deserializer=transfer__pb2.Empty.FromString,
                    response_serializer=transfer__pb2.ListPermission.SerializeToString,
            ),
            'GetTPMPermission': grpc.unary_stream_rpc_method_handler(
                    servicer.GetTPMPermission,
                    request_deserializer=transfer__pb2.Empty.FromString,
                    response_serializer=transfer__pb2.ListPermission.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transfer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transfer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTMOPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Transfer/GetTMOPermission',
            transfer__pb2.Empty.SerializeToString,
            transfer__pb2.ListPermission.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMOPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Transfer/GetMOPermission',
            transfer__pb2.Empty.SerializeToString,
            transfer__pb2.ListPermission.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTPMPermission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/Transfer/GetTPMPermission',
            transfer__pb2.Empty.SerializeToString,
            transfer__pb2.ListPermission.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
