MS_HIERARCHY_ROUTER_PREFIX = "/ms_hierarchy"


HIERARCHY_ROUTER_PREFIX = MS_HIERARCHY_ROUTER_PREFIX + "/hierarchy"


HIERARCHY_RELOAD_ROUTER_PREFIX = MS_HIERARCHY_ROUTER_PREFIX + "/reloader"


HIERARCHY_INFO_ROUTER_PREFIX = MS_HIERARCHY_ROUTER_PREFIX + "/info"
