# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistic.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fstatistic.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xda\x03\n\tStatistic\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tgroupName\x18\x03 \x01(\t\x12$\n\x03pov\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\x12)\n\x08geometry\x18\x05 \x01(\x0b\x32\x17.google.protobuf.Struct\x12\x0e\n\x06\x61\x63tive\x18\x06 \x01(\x08\x12\x10\n\x08latitude\x18\x07 \x01(\x01\x12\x11\n\tlongitude\x18\x08 \x01(\x01\x12\x0e\n\x06tmo_id\x18\t \x01(\x03\x12\x0c\n\x04p_id\x18\n \x01(\x03\x12\x12\n\npoint_a_id\x18\x0b \x01(\x03\x12\x12\n\npoint_b_id\x18\x0c \x01(\x03\x12\r\n\x05model\x18\r \x01(\t\x12\x0f\n\x07version\x18\x0e \x01(\x05\x12\x0e\n\x06status\x18\x0f \x01(\t\x12\x31\n\rcreation_date\x18\x10 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x11modification_date\x18\x11 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0e\n\x06params\x18\x12 \x01(\t\x12\x16\n\x0e\x64ocument_count\x18\x13 \x01(\x05\x12\x12\n\ngroup_type\x18\x14 \x01(\t\"$\n\x0f\x44\x65leteStatistic\x12\x11\n\tgroupName\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATISTIC']._serialized_start=83
  _globals['_STATISTIC']._serialized_end=557
  _globals['_DELETESTATISTIC']._serialized_start=559
  _globals['_DELETESTATISTIC']._serialized_end=595
# @@protoc_insertion_point(module_scope)
