# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search_severity.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15search_severity.proto\x12\x0fsearch_severity\"\x1e\n\x0b\x46ilterInput\x12\x0f\n\x07\x66ilters\x18\x01 \x03(\t\"P\n\x14ResponseSeverityItem\x12\x13\n\x0b\x66ilter_name\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x14\n\x0cmax_severity\x18\x03 \x01(\x02\"L\n\x14ListResponseSeverity\x12\x34\n\x05items\x18\x01 \x03(\x0b\x32%.search_severity.ResponseSeverityItem\"c\n\rByRangesInput\x12\x14\n\x0c\x66ilters_list\x18\x01 \x03(\t\x12\x15\n\rranges_object\x18\x02 \x01(\t\x12\x0e\n\x06tmo_id\x18\x03 \x01(\x05\x12\x15\n\rfind_by_value\x18\x04 \x01(\t\"\xd9\x01\n\x0eProcessesInput\x12\x14\n\x0c\x66ilters_list\x18\x01 \x03(\t\x12\x1a\n\rranges_object\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x0e\n\x06tmo_id\x18\x03 \x01(\x05\x12\x0c\n\x04sort\x18\x04 \x03(\t\x12\r\n\x05limit\x18\x05 \x01(\t\x12\x1a\n\rfind_by_value\x18\x06 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0bwith_groups\x18\x07 \x01(\x08H\x02\x88\x01\x01\x42\x10\n\x0e_ranges_objectB\x10\n\x0e_find_by_valueB\x0e\n\x0c_with_groups\"6\n\x11ProcessesResponse\x12\x0c\n\x04rows\x18\x01 \x03(\t\x12\x13\n\x0btotal_count\x18\x02 \x01(\x05\x32\xa6\x02\n\x0eSearchSeverity\x12]\n\x14GetSeverityByFilters\x12\x1c.search_severity.FilterInput\x1a%.search_severity.ListResponseSeverity\"\x00\x12^\n\x13GetSeverityByRanges\x12\x1e.search_severity.ByRangesInput\x1a%.search_severity.ListResponseSeverity\"\x00\x12U\n\x0cGetProcesses\x12\x1f.search_severity.ProcessesInput\x1a\".search_severity.ProcessesResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'search_severity_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILTERINPUT']._serialized_start=42
  _globals['_FILTERINPUT']._serialized_end=72
  _globals['_RESPONSESEVERITYITEM']._serialized_start=74
  _globals['_RESPONSESEVERITYITEM']._serialized_end=154
  _globals['_LISTRESPONSESEVERITY']._serialized_start=156
  _globals['_LISTRESPONSESEVERITY']._serialized_end=232
  _globals['_BYRANGESINPUT']._serialized_start=234
  _globals['_BYRANGESINPUT']._serialized_end=333
  _globals['_PROCESSESINPUT']._serialized_start=336
  _globals['_PROCESSESINPUT']._serialized_end=553
  _globals['_PROCESSESRESPONSE']._serialized_start=555
  _globals['_PROCESSESRESPONSE']._serialized_end=609
  _globals['_SEARCHSEVERITY']._serialized_start=612
  _globals['_SEARCHSEVERITY']._serialized_end=906
# @@protoc_insertion_point(module_scope)
