# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import search_severity_pb2 as search__severity__pb2


class SearchSeverityStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSeverityByFilters = channel.unary_unary(
                '/search_severity.SearchSeverity/GetSeverityByFilters',
                request_serializer=search__severity__pb2.FilterInput.SerializeToString,
                response_deserializer=search__severity__pb2.ListResponseSeverity.FromString,
                )
        self.GetSeverityByRanges = channel.unary_unary(
                '/search_severity.SearchSeverity/GetSeverityByRanges',
                request_serializer=search__severity__pb2.ByRangesInput.SerializeToString,
                response_deserializer=search__severity__pb2.ListResponseSeverity.FromString,
                )
        self.GetProcesses = channel.unary_unary(
                '/search_severity.SearchSeverity/GetProcesses',
                request_serializer=search__severity__pb2.ProcessesInput.SerializeToString,
                response_deserializer=search__severity__pb2.ProcessesResponse.FromString,
                )


class SearchSeverityServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSeverityByFilters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeverityByRanges(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SearchSeverityServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSeverityByFilters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeverityByFilters,
                    request_deserializer=search__severity__pb2.FilterInput.FromString,
                    response_serializer=search__severity__pb2.ListResponseSeverity.SerializeToString,
            ),
            'GetSeverityByRanges': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeverityByRanges,
                    request_deserializer=search__severity__pb2.ByRangesInput.FromString,
                    response_serializer=search__severity__pb2.ListResponseSeverity.SerializeToString,
            ),
            'GetProcesses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcesses,
                    request_deserializer=search__severity__pb2.ProcessesInput.FromString,
                    response_serializer=search__severity__pb2.ProcessesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'search_severity.SearchSeverity', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SearchSeverity(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSeverityByFilters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/search_severity.SearchSeverity/GetSeverityByFilters',
            search__severity__pb2.FilterInput.SerializeToString,
            search__severity__pb2.ListResponseSeverity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSeverityByRanges(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/search_severity.SearchSeverity/GetSeverityByRanges',
            search__severity__pb2.ByRangesInput.SerializeToString,
            search__severity__pb2.ListResponseSeverity.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProcesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/search_severity.SearchSeverity/GetProcesses',
            search__severity__pb2.ProcessesInput.SerializeToString,
            search__severity__pb2.ProcessesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
