# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: group.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgroup.proto\"V\n\x05GROUP\x12\x12\n\ngroup_name\x18\x01 \x01(\t\x12\x15\n\tentity_id\x18\x02 \x03(\x05\x42\x02\x10\x01\x12\x12\n\ngroup_type\x18\x03 \x01(\t\x12\x0e\n\x06tmo_id\x18\x04 \x01(\x03*0\n\tGroupType\x12\x10\n\x0cobject_group\x10\x00\x12\x11\n\rprocess_group\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'group_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GROUP'].fields_by_name['entity_id']._loaded_options = None
  _globals['_GROUP'].fields_by_name['entity_id']._serialized_options = b'\020\001'
  _globals['_GROUPTYPE']._serialized_start=103
  _globals['_GROUPTYPE']._serialized_end=151
  _globals['_GROUP']._serialized_start=15
  _globals['_GROUP']._serialized_end=101
# @@protoc_insertion_point(module_scope)
